return {
	name = "autogen-types",
	dir = vim.fn.stdpath("config"),
	config = function()
		-- 1. Notify that the plugin is loading
		local function generate_color_types()
			local colors = vim.fn.getcompletion("", "color")

			local lines = {
				"---@meta",
				"-- This file is autogenerated by :GenTypes command",
				"---@alias MyColors",
			}

			for _, name in ipairs(colors) do
				table.insert(lines, ('---| "%s"'):format(name))
			end

			local path = vim.fn.stdpath("config") .. "/lua/generated_types.lua"
			local f = io.open(path, "w")
			if f then
				f:write(table.concat(lines, "\n"))
				f:close()
				vim.notify("Generated types to " .. path, vim.log.levels.INFO)
			else
				vim.notify("Failed to write types file", vim.log.levels.ERROR)
			end
		end

		-- 2. Create the command
		vim.api.nvim_create_user_command("GenTypes", function()
			generate_color_types()
		end, { desc = "Generate colorscheme types for autocomplete" })

		-- 3. Run it once on load so types are always fresh
		generate_color_types()
	end,
}
